const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/authController');
const authenticate = require('../middleware/auth');
router.post('/register-org', ctrl.registerOrg);
router.post('/login', ctrl.login);
router.post('/refresh', ctrl.refresh);
router.post('/logout', ctrl.logout);
router.get('/me', authenticate, ctrl.me);
router.post('/change-password', authenticate, ctrl.changePassword);
router.get('/sessions', authenticate, ctrl.sessions);
router.delete('/sessions/:id', authenticate, ctrl.revokeSession);
module.exports = router;
