const express = require('express');
const router = express.Router();
const authenticate = require('../middleware/auth');
const { checkPermission } = require('../middleware/checkPermission');
const { checkBranchAccess } = require('../middleware/branchAccess');
const ctrl = require('../controllers/boqController');
router.use(authenticate, checkBranchAccess);
router.get('/compare', checkPermission('boq:view'), ctrl.compare);
router.get('/templates', checkPermission('boq:view'), ctrl.listTemplates);
router.post('/templates', checkPermission('boq:create'), ctrl.createTemplate);
router.post('/templates/:tplId/instantiate', checkPermission('boq:create'), ctrl.instantiateTemplate);
router.get('/', checkPermission('boq:view'), ctrl.list);
router.post('/', checkPermission('boq:create'), ctrl.create);
router.get('/:id', checkPermission('boq:view'), ctrl.get);
router.get('/:id/revisions', checkPermission('boq:view'), ctrl.revisions);
router.get('/:id/history', checkPermission('boq:view'), ctrl.history);
router.get('/:id/cost-control', checkPermission('boq:view'), ctrl.costControl);
router.get('/:id/export', checkPermission('boq:view'), ctrl.exportXlsx);
router.post('/:id/items', checkPermission('boq:edit'), ctrl.addItem);
router.put('/:id/items/:itemId', checkPermission('boq:edit'), ctrl.updateItem);
router.delete('/:id/items/:itemId', checkPermission('boq:edit'), ctrl.removeItem);
router.post('/:id/transition', checkPermission('boq:edit'), ctrl.transition);
router.post('/:id/approve', checkPermission('boq:approve'), ctrl.approve);
router.post('/:id/new-revision', checkPermission('boq:create'), ctrl.newRevision);
router.post('/:id/bill', checkPermission('ipc:create'), ctrl.billRemaining);
module.exports = router;
