const express = require('express');
const router = express.Router();
const authenticate = require('../middleware/auth');
const { checkPermission } = require('../middleware/checkPermission');
const { checkBranchAccess } = require('../middleware/branchAccess');
const ctrl = require('../controllers/estimationController');
router.use(authenticate, checkBranchAccess);
router.get('/', checkPermission('estimation:view'), ctrl.list);
router.get('/:id', checkPermission('estimation:view'), ctrl.get);
router.get('/:id/export', checkPermission('estimation:view'), ctrl.exportXlsx);
router.post('/', checkPermission('estimation:create'), ctrl.create);
router.put('/:id', checkPermission('estimation:edit'), ctrl.updateHeader);
router.post('/:id/items', checkPermission('estimation:edit'), ctrl.addItem);
router.put('/:id/items/:itemId', checkPermission('estimation:edit'), ctrl.updateItem);
router.delete('/:id/items/:itemId', checkPermission('estimation:edit'), ctrl.removeItem);
router.post('/:id/transition', checkPermission('estimation:edit'), ctrl.transition);
router.post('/:id/approve', checkPermission('estimation:approve'), ctrl.approve);
router.post('/:id/new-revision', checkPermission('estimation:approve'), ctrl.newRevision);
module.exports = router;
