const express = require('express');
const router = express.Router();
const auditLogger = require('../middleware/auditLogger');
router.use(auditLogger());
router.get('/ping', (req, res) => res.json({ status: 'success', message: 'qulf api' }));
router.use('/auth', require('./auth'));
router.use('/users', require('./users'));
router.use('/roles', require('./roles'));
router.use('/branches', require('./branches'));
router.use('/settings', require('./settings'));
router.use('/customers', require('./customers'));
router.use('/guarantees', require('./guarantees'));
router.use('/projects', require('./projects'));
router.use('/boqs', require('./boqs'));
router.use('/estimations', require('./estimations'));
router.use('/tenders', require('./tenders'));
router.use('/ipc', require('./ipc'));
router.use('/procurement', require('./procurement'));
router.use('/subcontract', require('./subcontract'));
router.use('/site', require('./site'));
router.use('/documents', require('./documents'));
router.use('/dashboard', require('./dashboard'));
router.use('/boqs', require('./boqImport'));
router.use('/organizations', require('./organizations'));
module.exports = router;
