const express = require('express');
const router = express.Router();
const authenticate = require('../middleware/auth');
const { checkPermission } = require('../middleware/checkPermission');
const { checkBranchAccess } = require('../middleware/branchAccess');
const c = require('../controllers/procurementController');
const items = require('../controllers/itemController');
router.use(authenticate, checkBranchAccess);
router.get('/suppliers', checkPermission('procurement:view'), c.listSuppliers);
router.post('/suppliers', checkPermission('procurement:create'), c.createSupplier);
router.get('/materials', checkPermission('procurement:view'), c.listMaterials);
router.post('/materials', checkPermission('procurement:create'), c.createMaterial);
// Full item master
router.get('/items', checkPermission('procurement:view'), items.catalog);
router.post('/items', checkPermission('procurement:create'), items.create);
router.get('/items/:id', checkPermission('procurement:view'), items.get);
router.put('/items/:id', checkPermission('procurement:create'), items.update);
router.delete('/items/:id', checkPermission('procurement:delete'), items.remove);
router.post('/items/:id/duplicate', checkPermission('procurement:create'), items.duplicate);
router.post('/items/:id/prices', checkPermission('procurement:create'), items.addPrice);
router.put('/items/prices/:priceId', checkPermission('procurement:create'), items.updatePrice);
router.delete('/items/prices/:priceId', checkPermission('procurement:delete'), items.removePrice);
router.post('/items/:id/specs', checkPermission('procurement:create'), items.addSpec);
router.put('/items/specs/:specId', checkPermission('procurement:create'), items.updateSpec);
router.delete('/items/specs/:specId', checkPermission('procurement:delete'), items.removeSpec);
router.get('/reorder', checkPermission('procurement:view'), c.reorder);
router.get('/indents', checkPermission('procurement:view'), c.listIndents);
router.post('/indents', checkPermission('procurement:create'), c.createIndent);
router.post('/indents/:id/decision', checkPermission('procurement:approve'), c.indentDecision);
router.get('/quotations', checkPermission('procurement:view'), c.listQuotations);
router.post('/quotations', checkPermission('procurement:create'), c.createQuotation);
router.post('/quotations/:id/select', checkPermission('procurement:approve'), c.selectQuotation);
router.get('/pos', checkPermission('procurement:view'), c.listPOs);
router.post('/pos', checkPermission('procurement:create'), c.createPO);
router.post('/pos/:id/approve', checkPermission('procurement:approve'), c.approvePO);
router.get('/grns', checkPermission('procurement:view'), c.listGRNs);
router.post('/grns', checkPermission('procurement:create'), c.createGRN);
router.post('/grns/:id/post', checkPermission('procurement:approve'), c.postGRN);
router.get('/stock', checkPermission('procurement:view'), c.siteStock);
module.exports = router;
