const express = require('express');
const router = express.Router();
const authenticate = require('../middleware/auth');
const { checkPermission } = require('../middleware/checkPermission');
const { checkBranchAccess } = require('../middleware/branchAccess');
const c = require('../controllers/procurementController');
router.use(authenticate, checkBranchAccess);
router.get('/suppliers', checkPermission('procurement:view'), c.listSuppliers);
router.post('/suppliers', checkPermission('procurement:create'), c.createSupplier);
router.get('/materials', checkPermission('procurement:view'), c.listMaterials);
router.post('/materials', checkPermission('procurement:create'), c.createMaterial);
router.get('/reorder', checkPermission('procurement:view'), c.reorder);
router.get('/indents', checkPermission('procurement:view'), c.listIndents);
router.post('/indents', checkPermission('procurement:create'), c.createIndent);
router.post('/indents/:id/decision', checkPermission('procurement:approve'), c.indentDecision);
router.get('/quotations', checkPermission('procurement:view'), c.listQuotations);
router.post('/quotations', checkPermission('procurement:create'), c.createQuotation);
router.post('/quotations/:id/select', checkPermission('procurement:approve'), c.selectQuotation);
router.get('/pos', checkPermission('procurement:view'), c.listPOs);
router.post('/pos', checkPermission('procurement:create'), c.createPO);
router.post('/pos/:id/approve', checkPermission('procurement:approve'), c.approvePO);
router.get('/grns', checkPermission('procurement:view'), c.listGRNs);
router.post('/grns', checkPermission('procurement:create'), c.createGRN);
router.post('/grns/:id/post', checkPermission('procurement:approve'), c.postGRN);
router.get('/stock', checkPermission('procurement:view'), c.siteStock);
module.exports = router;
