const express = require('express');
const router = express.Router();
const authenticate = require('../middleware/auth');
const { checkPermission } = require('../middleware/checkPermission');
const { checkBranchAccess } = require('../middleware/branchAccess');
const ctrl = require('../controllers/projectController');
router.use(authenticate, checkBranchAccess);
router.get('/', checkPermission('project:view'), ctrl.list);
router.post('/', checkPermission('project:create'), ctrl.create);
router.delete('/bulk', checkPermission('project:edit'), ctrl.bulkRemove);
router.get('/:id', checkPermission('project:view'), ctrl.get);
router.get('/:id/activity', checkPermission('project:view'), ctrl.activity);
router.put('/:id', checkPermission('project:edit'), ctrl.update);
router.post('/:id/transition', checkPermission('project:edit'), ctrl.transition);
router.delete('/:id', checkPermission('project:edit'), ctrl.remove);
router.post('/:id/budget', checkPermission('project:edit'), ctrl.saveBudget);
router.get('/:id/budget-vs-actual', checkPermission('project:view'), ctrl.budgetVsActual);
router.get('/:id/advances', checkPermission('project:view'), ctrl.listAdvances);
router.post('/:id/advances', checkPermission('project:create'), ctrl.createAdvance);
router.post('/:id/advances/:advId/receive', checkPermission('project:edit'), ctrl.receiveAdvance);
router.get('/:id/advances-balance', checkPermission('project:view'), ctrl.advanceBalance);
router.get('/:id/members', checkPermission('project:view'), ctrl.listMembers);
router.post('/:id/members', checkPermission('project:create'), ctrl.addMember);
router.delete('/:id/members/:memberId', checkPermission('project:edit'), ctrl.removeMember);
module.exports = router;
