const express = require('express');
const router = express.Router();
const authenticate = require('../middleware/auth');
const { checkPermission } = require('../middleware/checkPermission');
const { checkBranchAccess } = require('../middleware/branchAccess');
const ctrl = require('../controllers/tenderController');
router.use(authenticate, checkBranchAccess);
router.get('/analytics', checkPermission('tender:view'), ctrl.summary);
router.get('/', checkPermission('tender:view'), ctrl.list);
router.get('/:id', checkPermission('tender:view'), ctrl.get);
router.get('/:id/cost-analysis', checkPermission('tender:view'), ctrl.costAnalysis);
router.get('/:id/history', checkPermission('tender:view'), ctrl.history);
router.get('/:id/export', checkPermission('tender:view'), ctrl.exportXlsx);
router.get('/:id/documents', checkPermission('tender:view'), ctrl.listDocs);
router.get('/:id/addenda', checkPermission('tender:view'), ctrl.listAddenda);
router.post('/', checkPermission('tender:create'), ctrl.create);
router.put('/:id', checkPermission('tender:create'), ctrl.update);
router.delete('/:id', checkPermission('tender:delete'), ctrl.remove);
router.post('/:id/submit', checkPermission('tender:create'), ctrl.submit);
router.post('/:id/freeze-baseline', checkPermission('tender:create'), ctrl.freezeBaseline);
router.post('/:id/decision', checkPermission('tender:create'), ctrl.decision);
router.post('/:id/convert', checkPermission('tender:create'), ctrl.convertToProject);
router.post('/:id/addenda', checkPermission('tender:create'), ctrl.addAddendum);
router.put('/:id/addenda/:addendumId/answer', checkPermission('tender:create'), ctrl.answerAddendum);
router.delete('/:id/addenda/:addendumId', checkPermission('tender:create'), ctrl.removeAddendum);
module.exports = router;
